# Generated by Django 4.0.1 on 2022-04-08 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(default='空', max_length=8, unique=True, verbose_name='部门名称')),
                ('department_message', models.CharField(default='空', max_length=256, verbose_name='部门信息')),
            ],
        ),
        migrations.CreateModel(
            name='DetailedInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('det_name', models.CharField(default='空', max_length=8, unique=True, verbose_name='姓名')),
                ('det_set', models.CharField(choices=[('男', '男'), ('女', '女')], default='fulltime', max_length=4, verbose_name='性别')),
                ('det_age', models.IntegerField(default=1, verbose_name='年龄')),
                ('det_number', models.CharField(default='DF', max_length=16, verbose_name='工号')),
                ('det_address', models.CharField(default='浙江', max_length=24, verbose_name='地址')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emergency.department', to_field='department_name')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=128, unique=True, verbose_name='图片名称')),
                ('image_type', models.CharField(max_length=16, verbose_name='图片类型')),
                ('image_path', models.CharField(max_length=64, verbose_name='图片路径')),
                ('image_base', models.BinaryField(verbose_name='图片编码')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_info', models.CharField(default='空', max_length=128, verbose_name='新闻信息')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='未填写', max_length=8, unique=True)),
                ('number', models.CharField(default='未填写', max_length=24, unique=True)),
                ('password', models.CharField(default='未填写', max_length=64)),
                ('is_active', models.BinaryField(default=True)),
                ('detailedInfo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='emergency.detailedinfo')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencySupplies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplies_name', models.CharField(max_length=16, unique=True, verbose_name='物资名称')),
                ('supplies_price', models.FloatField(verbose_name='物资价格')),
                ('supplies_quantity', models.IntegerField(verbose_name='物资数量')),
                ('supplies_info', models.CharField(choices=[('北京供应商', '北京供应商'), ('上海供应商', '上海供应商'), ('浙江供应商', '浙江供应商')], default='fulltime', max_length=32, verbose_name='供应商信息')),
                ('supplies_type', models.CharField(choices=[('食物', '食物'), ('防护', '防护'), ('水', '水'), ('日常用品', '日常用品')], default='fulltime', max_length=32, verbose_name='物资类型')),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='emergency.image', to_field='image_name')),
            ],
        ),
    ]
