# Generated by Django 4.0.1 on 2022-04-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
        ('emergency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailedinfo',
            name='det_ph',
            field=models.CharField(default='123', max_length=20, verbose_name='电话'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='roles',
            field=models.ManyToManyField(to='rbac.Role'),
        ),
    ]
