# Generated by Django 4.0.1 on 2022-04-09 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0002_detailedinfo_det_ph_userinfo_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='detailedInfo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emergency.detailedinfo'),
        ),
    ]
