# Generated by Django 4.0.1 on 2022-04-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0003_alter_userinfo_detailedinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_message',
            field=models.CharField(default='空', max_length=1024, verbose_name='部门信息'),
        ),
    ]
