# Generated by Django 4.0.1 on 2022-04-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0004_alter_department_department_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpidemicSituation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(default='未填写', max_length=16, verbose_name='地区')),
                ('number', models.IntegerField(default=0, max_length=8, verbose_name='地区人数')),
                ('infections_number', models.IntegerField(default=0, max_length=6, verbose_name='感染人数')),
                ('infections_proportion', models.FloatField(default=0, max_length=3, verbose_name='比例')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplies_name', models.CharField(max_length=16, unique=True, verbose_name='物资名称')),
                ('supplies_quantity', models.IntegerField(verbose_name='物资数量')),
                ('supplies_type', models.CharField(choices=[('食物', '食物'), ('防护', '防护'), ('水', '水'), ('日常用品', '日常用品')], max_length=32, verbose_name='物资类型')),
            ],
        ),
    ]
