# Generated by Django 4.0.1 on 2022-04-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0005_epidemicsituation_materialrequirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epidemicsituation',
            name='infections_proportion',
            field=models.FloatField(default=0, verbose_name='比例'),
        ),
        migrations.AlterField(
            model_name='epidemicsituation',
            name='number',
            field=models.IntegerField(default=0, verbose_name='地区人数'),
        ),
    ]
