# Generated by Django 4.0.1 on 2022-04-10 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0007_alter_epidemicsituation_infections_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='epidemicsituation',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emergency.materialrequirements'),
        ),
    ]
