# Generated by Django 4.0.1 on 2022-04-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0009_remove_epidemicsituation_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epidemicsituation',
            name='material',
            field=models.ManyToManyField(to='emergency.MaterialRequirements'),
        ),
    ]
