# Generated by Django 4.0.1 on 2022-04-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0010_alter_epidemicsituation_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epidemicsituation',
            name='material',
        ),
        migrations.AlterField(
            model_name='materialrequirements',
            name='supplies_quantity',
            field=models.CharField(default='箱', max_length=8, verbose_name='物资单位'),
        ),
        migrations.CreateModel(
            name='RegionalDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regional_name', models.CharField(choices=[('平岩市', '平岩市'), ('清州市', '清州市'), ('安中市', '安中市'), ('辽山市', '辽山市'), ('东义市', '东义市')], default='fulltime', max_length=8, verbose_name='地区名')),
                ('sup_num', models.IntegerField(default=0, verbose_name='需求物资数')),
                ('material', models.ManyToManyField(to='emergency.MaterialRequirements')),
            ],
        ),
    ]
