# Generated by Django 4.0.1 on 2022-04-10 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0011_remove_epidemicsituation_material_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialrequirements',
            old_name='supplies_quantity',
            new_name='supplies_unit',
        ),
    ]
