# Generated by Django 4.0.1 on 2022-04-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0012_rename_supplies_quantity_materialrequirements_supplies_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regionaldemand',
            name='material',
        ),
        migrations.AddField(
            model_name='regionaldemand',
            name='supplies_name',
            field=models.CharField(default='未填写', max_length=16, unique=True, verbose_name='物资名称'),
        ),
        migrations.AddField(
            model_name='regionaldemand',
            name='supplies_type',
            field=models.CharField(choices=[('食物', '食物'), ('防护', '防护'), ('水', '水'), ('日常用品', '日常用品')], default='fulltime', max_length=32, verbose_name='物资类型'),
        ),
        migrations.AddField(
            model_name='regionaldemand',
            name='supplies_unit',
            field=models.CharField(default='箱', max_length=8, verbose_name='物资单位'),
        ),
        migrations.DeleteModel(
            name='MaterialRequirements',
        ),
    ]
