# Generated by Django 4.0.1 on 2022-04-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0013_remove_regionaldemand_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionaldemand',
            name='state',
            field=models.CharField(choices=[('未处理', '未处理'), ('已处理', '已处理')], default='未处理', max_length=8, verbose_name='需求处理状态'),
        ),
    ]
