# Generated by Django 4.0.1 on 2022-04-10 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0014_regionaldemand_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionaldemand',
            name='procurement_state',
            field=models.CharField(choices=[('未处理', '未处理'), ('已处理', '已处理')], default='未处理', max_length=8, verbose_name='采购部门处理状态'),
        ),
        migrations.AlterField(
            model_name='regionaldemand',
            name='state',
            field=models.CharField(choices=[('未处理', '未处理'), ('已处理', '已处理')], default='未处理', max_length=8, verbose_name='需求部门处理状态'),
        ),
    ]
