# Generated by Django 4.0.1 on 2022-04-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0017_regionaldemand_failure_why'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionaldemand',
            name='sums',
            field=models.IntegerField(default=0, verbose_name='总价'),
        ),
    ]
