# Generated by Django 4.0.1 on 2022-04-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0020_regionaldemand_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deploy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_address', models.CharField(choices=[('平岩市', '平岩市'), ('清州市', '清州市'), ('安中市', '安中市'), ('辽山市', '辽山市'), ('东义市', '东义市')], default='未选择', max_length=4, verbose_name='调配地区')),
                ('d_name', models.CharField(default='未填写', max_length=16, verbose_name='物资名称')),
                ('d_number', models.IntegerField(default=0, verbose_name='调配物资数量')),
            ],
        ),
    ]
