# Generated by Django 4.0.1 on 2022-04-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0021_deploy'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploy',
            name='process_state',
            field=models.CharField(choices=[('未处理', '未处理'), ('已处理', '已处理')], default='未处理', max_length=6, verbose_name='处理状态'),
        ),
        migrations.AddField(
            model_name='deploy',
            name='transport_state',
            field=models.CharField(choices=[('已到达', '已到达'), ('运输中', '运输中')], default='未发车', max_length=6, verbose_name='运输状态'),
        ),
    ]
