# Generated by Django 4.0.1 on 2022-04-12 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0022_deploy_process_state_deploy_transport_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploy',
            name='d_type',
            field=models.CharField(choices=[('食物', '食物'), ('防护', '防护'), ('水', '水'), ('日常用品', '日常用品')], default='fulltime', max_length=32, verbose_name='物资类型'),
        ),
        migrations.AddField(
            model_name='deploy',
            name='d_unit',
            field=models.CharField(default='箱', max_length=8, verbose_name='物资单位'),
        ),
    ]
