# Generated by Django 4.0.1 on 2022-04-12 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0023_deploy_d_type_deploy_d_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploy',
            name='d_unit',
        ),
    ]
