# Generated by Django 4.0.1 on 2022-04-13 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0024_remove_deploy_d_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trucks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_number', models.CharField(default='未填写', max_length=16, verbose_name='货车编号')),
                ('truck_type', models.CharField(choices=[('2轴车', '2轴车'), ('3轴车', '3轴车'), ('4轴车', '4轴车'), ('5轴车', '5轴车'), ('6轴车及以上', '6轴车及以上')], default='未填写', max_length=8, verbose_name='货车型号')),
                ('truck_load', models.CharField(choices=[('2轴车', '2轴车'), ('3轴车', '3轴车'), ('4轴车', '4轴车'), ('5轴车', '5轴车'), ('6轴车及以上', '6轴车及以上')], default='未填写', max_length=8, verbose_name='货车载重')),
                ('truck_driver', models.CharField(choices=[('李强', '李强'), ('张虎', '张虎'), ('王守义', '王守义'), ('谢富贵', '谢富贵'), ('赵建国', '赵建国')], default='未填写', max_length=8, verbose_name='货车司机')),
            ],
        ),
    ]
