# Generated by Django 4.0.1 on 2022-04-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0026_trucksdeploy_alter_trucks_truck_load_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trucksdeploy',
            name='td_sup_type',
            field=models.CharField(choices=[('食物', '食物'), ('防护', '防护'), ('水', '水'), ('日常用品', '日常用品')], default='fulltime', max_length=32, verbose_name='物资类型'),
        ),
    ]
