# Generated by Django 4.0.1 on 2022-04-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0028_alter_trucks_truck_type_alter_trucksdeploy_td_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trucksdeploy',
            name='td_con',
            field=models.CharField(choices=[('已到达', '已到达'), ('运输中', '运输中')], default='未发车', max_length=8, verbose_name='发车情况'),
        ),
    ]
