# Generated by Django 4.0.1 on 2022-04-14 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0029_trucksdeploy_td_con'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploy',
            name='transport_state',
        ),
    ]
