# Generated by Django 4.0.1 on 2022-04-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0030_remove_deploy_transport_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrucksImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(default=0, verbose_name='报销费用')),
                ('cause', models.CharField(default='未填写', max_length=32, verbose_name='报销原因')),
                ('image_name', models.CharField(max_length=128, unique=True, verbose_name='图片名称')),
                ('image_path', models.CharField(max_length=64, verbose_name='图片路径')),
            ],
        ),
    ]
