# Generated by Django 4.0.1 on 2022-04-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0031_trucksimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='trucksimage',
            name='remark',
            field=models.CharField(default='空', max_length=64, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='trucksimage',
            name='status',
            field=models.CharField(choices=[('未处理', '未处理'), ('通过', '通过'), ('否决', '否决')], default='未处理', max_length=4, verbose_name='报销结果'),
        ),
    ]
