# Generated by Django 4.0.1 on 2022-04-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0035_purchasingresults_alter_deploy_d_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplies_name', models.CharField(max_length=64, unique=True, verbose_name='物资名称')),
                ('supplies_quantity', models.IntegerField(verbose_name='物资采购数量')),
                ('supplies_type', models.CharField(choices=[('防护用品类', '防护用品类'), ('生命救助类', '生命救助类'), ('生命支持类', '生命支持类'), ('临时食宿类', '临时食宿类'), ('污染清理类', '污染清理类'), ('器材工具类', '器材工具类'), ('工程材料类', '工程材料类'), ('医疗用品类', '医疗用品类')], default='fulltime', max_length=32, verbose_name='物资类型')),
                ('donor', models.CharField(default='未填写', max_length=32, verbose_name='捐赠者署名')),
            ],
        ),
        migrations.AlterField(
            model_name='deploy',
            name='d_type',
            field=models.CharField(choices=[('防护用品类', '防护用品类'), ('生命救助类', '生命救助类'), ('生命支持类', '生命支持类'), ('临时食宿类', '临时食宿类'), ('污染清理类', '污染清理类'), ('器材工具类', '器材工具类'), ('工程材料类', '工程材料类'), ('医疗用品类', '医疗用品类')], default='fulltime', max_length=32, verbose_name='物资类型'),
        ),
        migrations.AlterField(
            model_name='emergencysupplies',
            name='supplies_type',
            field=models.CharField(choices=[('防护用品类', '防护用品类'), ('生命救助类', '生命救助类'), ('生命支持类', '生命支持类'), ('临时食宿类', '临时食宿类'), ('污染清理类', '污染清理类'), ('器材工具类', '器材工具类'), ('工程材料类', '工程材料类'), ('医疗用品类', '医疗用品类')], default='fulltime', max_length=32, verbose_name='物资类型'),
        ),
        migrations.AlterField(
            model_name='materialsupplier',
            name='supplies_type',
            field=models.CharField(choices=[('防护用品类', '防护用品类'), ('生命救助类', '生命救助类'), ('生命支持类', '生命支持类'), ('临时食宿类', '临时食宿类'), ('污染清理类', '污染清理类'), ('器材工具类', '器材工具类'), ('工程材料类', '工程材料类'), ('医疗用品类', '医疗用品类')], default='fulltime', max_length=32, verbose_name='物资类型'),
        ),
        migrations.AlterField(
            model_name='purchasingresults',
            name='supplies_type',
            field=models.CharField(choices=[('防护用品类', '防护用品类'), ('生命救助类', '生命救助类'), ('生命支持类', '生命支持类'), ('临时食宿类', '临时食宿类'), ('污染清理类', '污染清理类'), ('器材工具类', '器材工具类'), ('工程材料类', '工程材料类'), ('医疗用品类', '医疗用品类')], default='fulltime', max_length=32, verbose_name='物资类型'),
        ),
        migrations.AlterField(
            model_name='regionaldemand',
            name='supplies_type',
            field=models.CharField(choices=[('防护用品类', '防护用品类'), ('生命救助类', '生命救助类'), ('生命支持类', '生命支持类'), ('临时食宿类', '临时食宿类'), ('污染清理类', '污染清理类'), ('器材工具类', '器材工具类'), ('工程材料类', '工程材料类'), ('医疗用品类', '医疗用品类')], default='fulltime', max_length=32, verbose_name='物资类型'),
        ),
        migrations.AlterField(
            model_name='trucksdeploy',
            name='td_sup_type',
            field=models.CharField(choices=[('防护用品类', '防护用品类'), ('生命救助类', '生命救助类'), ('生命支持类', '生命支持类'), ('临时食宿类', '临时食宿类'), ('污染清理类', '污染清理类'), ('器材工具类', '器材工具类'), ('工程材料类', '工程材料类'), ('医疗用品类', '医疗用品类')], default='fulltime', max_length=32, verbose_name='物资类型'),
        ),
    ]
