# Generated by Django 4.0.1 on 2022-04-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0037_socialdonation_supplies_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='warehouse_max_capacity',
            field=models.IntegerField(default=0, verbose_name='仓库最大容量(m³)'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='warehouse_surplus_capacity',
            field=models.IntegerField(default=0, verbose_name='仓库剩余容量(m³)'),
        ),
        migrations.AlterField(
            model_name='emergencysupplies',
            name='supplies_info',
            field=models.CharField(choices=[('京东本地仓', '京东本地仓'), ('天猫国际仓', '天猫国际仓'), ('天猫超市仓', '天猫超市仓'), ('巴迪高企业', '巴迪高企业'), ('哈拿户外企业', '哈拿户外企业'), ('麦德里企业', '麦德里企业'), ('甜橙商贸企业', '甜橙商贸企业'), ('亿家老小医疗器械企业', '亿家老小医疗器械企业'), ('迪立家居企业', '迪立家居企业'), ('碧之道企业', '碧之道企业'), ('雅艺企业', '雅艺企业'), ('蓝均医疗用品企业', '蓝均医疗用品企业'), ('蓝均医疗用品企业', '蓝均医疗用品企业'), ('益舒净企业', '益舒净企业'), ('益舒净企业', '益舒净企业'), ('罗兰企业', '罗兰企业'), ('怡宝企业', '怡宝企业'), ('哇哈哈企业', '哇哈哈企业'), ('农夫山泉集团', '农夫山泉集团'), ('哇哈哈企业', '哇哈哈企业'), ('冰露企业', '冰露企业'), ('白象企业', '白象企业'), ('康师傅企业', '康师傅企业'), ('金龙鱼企业', '金龙鱼企业'), ('阿里健康企业', '阿里健康企业'), ('苏宁易购企业', '苏宁易购企业'), ('社会捐赠物资', '社会捐赠物资')], default='fulltime', max_length=32, verbose_name='供应商信息'),
        ),
        migrations.AlterField(
            model_name='materialsupplier',
            name='supplies_info',
            field=models.CharField(choices=[('京东本地仓', '京东本地仓'), ('天猫国际仓', '天猫国际仓'), ('天猫超市仓', '天猫超市仓'), ('巴迪高企业', '巴迪高企业'), ('哈拿户外企业', '哈拿户外企业'), ('麦德里企业', '麦德里企业'), ('甜橙商贸企业', '甜橙商贸企业'), ('亿家老小医疗器械企业', '亿家老小医疗器械企业'), ('迪立家居企业', '迪立家居企业'), ('碧之道企业', '碧之道企业'), ('雅艺企业', '雅艺企业'), ('蓝均医疗用品企业', '蓝均医疗用品企业'), ('蓝均医疗用品企业', '蓝均医疗用品企业'), ('益舒净企业', '益舒净企业'), ('益舒净企业', '益舒净企业'), ('罗兰企业', '罗兰企业'), ('怡宝企业', '怡宝企业'), ('哇哈哈企业', '哇哈哈企业'), ('农夫山泉集团', '农夫山泉集团'), ('哇哈哈企业', '哇哈哈企业'), ('冰露企业', '冰露企业'), ('白象企业', '白象企业'), ('康师傅企业', '康师傅企业'), ('金龙鱼企业', '金龙鱼企业'), ('阿里健康企业', '阿里健康企业'), ('苏宁易购企业', '苏宁易购企业'), ('社会捐赠物资', '社会捐赠物资')], default='fulltime', max_length=32, verbose_name='供应商信息'),
        ),
        migrations.AlterField(
            model_name='purchasingresults',
            name='supplies_info',
            field=models.CharField(choices=[('京东本地仓', '京东本地仓'), ('天猫国际仓', '天猫国际仓'), ('天猫超市仓', '天猫超市仓'), ('巴迪高企业', '巴迪高企业'), ('哈拿户外企业', '哈拿户外企业'), ('麦德里企业', '麦德里企业'), ('甜橙商贸企业', '甜橙商贸企业'), ('亿家老小医疗器械企业', '亿家老小医疗器械企业'), ('迪立家居企业', '迪立家居企业'), ('碧之道企业', '碧之道企业'), ('雅艺企业', '雅艺企业'), ('蓝均医疗用品企业', '蓝均医疗用品企业'), ('蓝均医疗用品企业', '蓝均医疗用品企业'), ('益舒净企业', '益舒净企业'), ('益舒净企业', '益舒净企业'), ('罗兰企业', '罗兰企业'), ('怡宝企业', '怡宝企业'), ('哇哈哈企业', '哇哈哈企业'), ('农夫山泉集团', '农夫山泉集团'), ('哇哈哈企业', '哇哈哈企业'), ('冰露企业', '冰露企业'), ('白象企业', '白象企业'), ('康师傅企业', '康师傅企业'), ('金龙鱼企业', '金龙鱼企业'), ('阿里健康企业', '阿里健康企业'), ('苏宁易购企业', '苏宁易购企业'), ('社会捐赠物资', '社会捐赠物资')], default='fulltime', max_length=32, verbose_name='供应商信息'),
        ),
        migrations.AlterField(
            model_name='socialdonation',
            name='supplies_quantity',
            field=models.IntegerField(verbose_name='物资数量'),
        ),
    ]
