# Generated by Django 4.0.1 on 2022-04-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0038_warehouse_warehouse_max_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialdonation',
            name='deploy_state',
            field=models.CharField(choices=[('未处理', '未处理'), ('已处理', '已处理')], default='未处理', max_length=8, verbose_name='调配状态'),
        ),
        migrations.AddField(
            model_name='socialdonation',
            name='transportation_state',
            field=models.CharField(choices=[('未处理', '未处理'), ('已签收入库', '已签收入库')], default='未处理', max_length=8, verbose_name='运输状态'),
        ),
    ]
