# Generated by Django 4.0.1 on 2022-04-19 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0039_socialdonation_deploy_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasingresults',
            name='supplies_name',
            field=models.CharField(max_length=64, verbose_name='物资名称'),
        ),
    ]
