# Generated by Django 4.0.1 on 2022-04-21 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0040_alter_purchasingresults_supplies_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ware_name', models.CharField(choices=[('平岩仓', '平岩仓'), ('东义仓', '东义仓'), ('清州仓', '清州仓'), ('安中仓', '安中仓'), ('安中仓', '安中仓'), ('珠山中心仓', '珠山中心仓')], default='空', max_length=8, verbose_name='仓库名')),
                ('sup_name', models.CharField(default='空', max_length=8, verbose_name='物资名称')),
                ('deploy_number', models.IntegerField(default=0, verbose_name='调入数量')),
                ('transportation_state', models.CharField(choices=[('未处理', '未处理'), ('运输中', '运输中'), ('已签收入库', '已签收入库')], default='未处理', max_length=8, verbose_name='运输状态')),
            ],
        ),
        migrations.AlterField(
            model_name='socialdonation',
            name='transportation_state',
            field=models.CharField(choices=[('未处理', '未处理'), ('运输中', '运输中'), ('已签收入库', '已签收入库')], default='未处理', max_length=8, verbose_name='运输状态'),
        ),
    ]
