# Generated by Django 4.0.1 on 2022-04-21 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0042_deploywarehouse_sup_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trucks',
            name='truck_state',
            field=models.CharField(choices=[('空闲', '空闲'), ('忙碌', '忙碌')], default='空闲', max_length=8, verbose_name='货车状态'),
        ),
        migrations.AlterField(
            model_name='deploywarehouse',
            name='sup_type',
            field=models.CharField(choices=[('防护用品类', '防护用品类'), ('生命救助类', '生命救助类'), ('生命支持类', '生命支持类'), ('临时食宿类', '临时食宿类'), ('污染清理类', '污染清理类'), ('器材工具类', '器材工具类'), ('工程材料类', '工程材料类'), ('医疗用品类', '医疗用品类')], default='空', max_length=8, verbose_name='物资类型'),
        ),
    ]
