# Generated by Django 4.0.1 on 2022-04-22 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0043_trucks_truck_state_alter_deploywarehouse_sup_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trucksdeploy',
            name='nature',
            field=models.CharField(choices=[('库存', '库存'), ('社会捐赠', '社会捐赠')], default='库存', max_length=8, verbose_name='发车情况'),
        ),
    ]
