# Generated by Django 4.0.1 on 2022-04-22 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0044_trucksdeploy_nature'),
    ]

    operations = [
        migrations.AddField(
            model_name='trucksdeploy',
            name='td_address',
            field=models.CharField(default='未填写', max_length=16, verbose_name='调配地区'),
        ),
        migrations.AlterField(
            model_name='trucksdeploy',
            name='nature',
            field=models.CharField(choices=[('库存', '库存'), ('社会捐赠', '社会捐赠')], default='库存', max_length=8, verbose_name='物资性质'),
        ),
    ]
