# Generated by Django 4.0.1 on 2022-04-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0045_trucksdeploy_td_address_alter_trucksdeploy_nature'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencysupplies',
            name='txt_path',
            field=models.CharField(default='D:\\PycharmProjects\\emergencysystem\\static', max_length=64, unique=True, verbose_name='文件路径'),
        ),
    ]
