# Generated by Django 4.0.1 on 2022-04-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0046_emergencysupplies_txt_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencysupplies',
            name='supplies_unit',
            field=models.CharField(default='kg', max_length=16, verbose_name='物资单位'),
        ),
        migrations.AlterField(
            model_name='emergencysupplies',
            name='supplies_name',
            field=models.CharField(max_length=64, unique=True, verbose_name='物资名称'),
        ),
    ]
