# Generated by Django 4.0.1 on 2022-04-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0047_emergencysupplies_supplies_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionaldemand',
            name='supplies_name',
            field=models.CharField(default='未填写', max_length=16, verbose_name='物资名称'),
        ),
    ]
