# Generated by Django 4.0.1 on 2022-04-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0048_alter_regionaldemand_supplies_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_herf',
            field=models.CharField(default='http', max_length=256, verbose_name='新闻链接'),
        ),
    ]
